import { Injectable, signal, WritableSignal } from '@angular/core';
import { Pokemon } from './pokemon.model';

@Injectable({
  providedIn: 'root',
})
export class PokemonService {
  pokemon: WritableSignal<Pokemon[]> = signal([
    {
      id: 1,
      name: 'Bulbasaur',
      currentHealth: 25,
      maxHealth: 25,
      attack: 3,
      level: 1,
      experience: 0,
      evolutionLevel: 9,
      image: 'assets/Bulbasaur.png',
      locked: false,
    },
    {
      id: 11,
      name: 'Ivysaur',
      currentHealth: 40,
      maxHealth: 65,
      attack: 6,
      level: 9,
      experience: 0,
      evolutionLevel: 20,
      image: 'assets/Ivysaur.png',
      locked: true,
    },
    {
      id: 111,
      name: 'Venusaur',
      currentHealth: 60,
      maxHealth: 125,
      attack: 8,
      level: 20,
      experience: 0,
      image: 'assets/Venusaur.jpg',
      locked: true,
    },
    {
      id: 1111,
      name: 'Mega Venusaur',
      currentHealth: 175,
      maxHealth: 300,
      attack: 13,
      level: 9,
      experience: 0,
      image: 'assets/MegaVenusaur.jpg',
      locked: true,
    },
    {
      id: 2,
      name: 'Charmander',
      currentHealth: 20,
      maxHealth: 20,
      attack: 5,
      level: 1,
      experience: 0,
      evolutionLevel: 9,
      image: 'assets/Charmander.jpg',
      locked: false,
    },
    {
      id: 22,
      name: 'Charmeleon',
      currentHealth: 30,
      maxHealth: 50,
      attack: 7,
      level: 9,
      experience: 0,
      evolutionLevel: 20,
      image: 'assets/Charmeleon.jpg',
      locked: true,
    },
    {
      id: 222,
      name: 'Charizard',
      currentHealth: 50,
      maxHealth: 100,
      attack: 8,
      level: 20,
      experience: 0,
      image: 'assets/Charizard.jpg',
      locked: true,
    },
    {
      id: 2222,
      name: 'Mega Charizard',
      currentHealth: 150,
      maxHealth: 250,
      attack: 20,
      level: 0,
      experience: 0,
      image: 'assets/MegaCharizard.png',
      locked: true,
    },
    {
      id: 3,
      name: 'Squirtle',
      currentHealth: 15,
      maxHealth: 15,
      attack: 7,
      level: 1,
      experience: 0,
      evolutionLevel: 9,
      image: 'assets/Squirtle.jpg',
      locked: false,
    },
    {
      id: 33,
      name: 'Wartortle',
      currentHealth: 30,
      maxHealth: 45,
      attack: 8,
      level: 9,
      experience: 0,
      evolutionLevel: 20,
      image: 'assets/Wartortle.jpg',
      locked: true,
    },
    {
      id: 333,
      name: 'Blastoise',
      currentHealth: 40,
      maxHealth: 85,
      attack: 10,
      level: 20,
      experience: 0,
      image: 'assets/Blastoise.jpg',
      locked: true,
    },
    {
      id: 3333,
      name: 'Mega Blastoise',
      currentHealth: 115,
      maxHealth: 200,
      attack: 25,
      level: 0,
      experience: 0,
      image: 'assets/MegaBlastoise.jpg',
      locked: true,
    },
    {
      id: 4,
      name: 'Pikachu',
      currentHealth: 35,
      maxHealth: 35,
      attack: 12,
      level: 1,
      experience: 0,
      evolutionLevel: 12,
      image: 'assets/Pikachu.png',
      locked: true,
    },
    {
      id: 44,
      name: 'Raichu',
      currentHealth: 55,
      maxHealth: 90,
      attack: 18,
      level: 12,
      experience: 0,
      image: 'assets/Raichu.jpg',
      locked: true,
    },
    {
      id: 5,
      name: 'Eevee',
      currentHealth: 30,
      maxHealth: 30,
      attack: 10,
      level: 1,
      experience: 0,
      image: 'assets/Eevee.png',
      locked: true,
    },
  ]);
}
