import { Injectable, signal, WritableSignal } from '@angular/core';
import { Boss } from '../Models/boss.model';
import { BadgesService } from './badges.service';

@Injectable({
  providedIn: 'root',
})
export class BossService {
  Bosses: WritableSignal<Boss[]> = signal([
    {
      difficulty: 1,
      bossName: 'Brock',
      pokemon: [
        {
          id: 20,
          commonId: 20,
          name: 'Geodude',
          currentHealth: 25,
          maxHealth: 25,
          attack: 3,
          level: 5,
          experience: 0,
          image: 'assets/bosses/pokemon/Geodude.jpg',
          locked: false,
        },
        {
          id: 21,
          commonId: 21,
          name: 'Onix',
          currentHealth: 30,
          maxHealth: 30,
          attack: 3,
          level: 10,
          experience: 0,
          image: 'assets/bosses/pokemon/Onix.jpg',
          locked: false,
        },
        {
          id: 22,
          commonId: 22,
          name: 'Kabuto',
          currentHealth: 25,
          maxHealth: 25,
          attack: 3,
          level: 8,
          experience: 80,
          evolutionLevel: 9,
          image: 'assets/bosses/pokemon/Kabuto.jpg',
          locked: false,
        },
        {
          id: 2222,
          commonId: 22,
          name: 'Kabutops',
          currentHealth: 50,
          maxHealth: 50,
          attack: 12,
          level: 9,
          experience: 0,
          image: 'assets/bosses/pokemon/Kabutops.jpg',
          locked: true,
        },
      ],
      hiddenItems: ['', ''],
      heldBadgeIndex: 0,
      image: 'assets/bosses/trainers/Brock.jpg',
      encounterCount: 5,
    },
    {
      difficulty: 2,
      bossName: 'Misty',
      pokemon: [
        {
          id: 30,
          commonId: 30,
          name: 'Goldeen',
          currentHealth: 25,
          maxHealth: 25,
          attack: 3,
          level: 5,
          experience: 0,
          image: 'assets/bosses/pokemon/Goldeen.jpg',
          locked: false,
        },
        {
          id: 3131,
          commonId: 31,
          name: 'Starmie',
          currentHealth: 50,
          maxHealth: 50,
          attack: 5,
          level: 10,
          experience: 0,
          image: 'assets/bosses/pokemon/Starmie.jpg',
          locked: false,
        },
        {
          id: 31,
          commonId: 31,
          name: 'Psyduck',
          currentHealth: 40,
          maxHealth: 40,
          attack: 2,
          level: 12,
          experience: 0,
          image: 'assets/bosses/pokemon/Psyduck.png',
          locked: false,
        },
      ],
      hiddenItems: ['', ''],
      heldBadgeIndex: 1,
      image: 'assets/bosses/trainers/Misty.jpg',
      encounterCount: 5,
    },
  ]);
}
