import { Injectable, signal, WritableSignal } from '@angular/core';
import { Pokemon } from '../Models/pokemon.model';

@Injectable({
  providedIn: 'root',
})
export class PokemonService {
  pokemon: WritableSignal<Pokemon[]> = signal([
    {
      id: 1,
      commonId: 1,
      name: 'Bulbasaur',
      currentHealth: 25,
      maxHealth: 25,
      attack: 3,
      level: 1,
      experience: 0,
      evolutionLevel: 9,
      image: 'assets/player-pokemon/Bulbasaur.png',
      locked: false,
    },
    {
      id: 11,
      commonId: 1,
      name: 'Ivysaur',
      currentHealth: 65,
      maxHealth: 65,
      attack: 9,
      level: 9,
      experience: 0,
      evolutionLevel: 20,
      image: 'assets/player-pokemon/Ivysaur.png',
      locked: true,
    },
    {
      id: 111,
      commonId: 1,
      name: 'Venusaur',
      currentHealth: 125,
      maxHealth: 125,
      attack: 17,
      level: 20,
      experience: 0,
      image: 'assets/player-pokemon/Venusaur.jpg',
      locked: true,
    },
    {
      id: 1111,
      commonId: 1,
      name: 'Mega Venusaur',
      currentHealth: 300,
      maxHealth: 300,
      attack: 30,
      level: 9,
      experience: 0,
      image: 'assets/player-pokemon/MegaVenusaur.jpg',
      locked: true,
    },
    {
      id: 2,
      commonId: 2,
      name: 'Charmander',
      currentHealth: 20,
      maxHealth: 20,
      attack: 5,
      level: 1,
      experience: 0,
      evolutionLevel: 9,
      image: 'assets/player-pokemon/Charmander.jpg',
      locked: false,
    },
    {
      id: 22,
      commonId: 2,
      name: 'Charmeleon',
      currentHealth: 50,
      maxHealth: 50,
      attack: 12,
      level: 9,
      experience: 0,
      evolutionLevel: 20,
      image: 'assets/player-pokemon/Charmeleon.jpg',
      locked: true,
    },
    {
      id: 222,
      commonId: 2,
      name: 'Charizard',
      currentHealth: 100,
      maxHealth: 100,
      attack: 20,
      level: 20,
      experience: 0,
      image: 'assets/player-pokemon/Charizard.jpg',
      locked: true,
    },
    {
      id: 2222,
      commonId: 2,
      name: 'Mega Charizard',
      currentHealth: 250,
      maxHealth: 250,
      attack: 40,
      level: 0,
      experience: 0,
      image: 'assets/player-pokemon/MegaCharizard.png',
      locked: true,
    },
    {
      id: 3,
      commonId: 3,
      name: 'Squirtle',
      currentHealth: 15,
      maxHealth: 15,
      attack: 7,
      level: 1,
      experience: 0,
      evolutionLevel: 9,
      image: 'assets/player-pokemon/Squirtle.jpg',
      locked: false,
    },
    {
      id: 33,
      commonId: 3,
      name: 'Wartortle',
      currentHealth: 45,
      maxHealth: 45,
      attack: 15,
      level: 9,
      experience: 0,
      evolutionLevel: 20,
      image: 'assets/player-pokemon/Wartortle.jpg',
      locked: true,
    },
    {
      id: 333,
      commonId: 3,
      name: 'Blastoise',
      currentHealth: 85,
      maxHealth: 85,
      attack: 25,
      level: 20,
      experience: 0,
      image: 'assets/player-pokemon/Blastoise.jpg',
      locked: true,
    },
    {
      id: 3333,
      commonId: 3,
      name: 'Mega Blastoise',
      currentHealth: 200,
      maxHealth: 200,
      attack: 50,
      level: 0,
      experience: 0,
      image: 'assets/player-pokemon/MegaBlastoise.jpg',
      locked: true,
    },
    {
      id: 4,
      commonId: 4,
      name: 'Pikachu',
      currentHealth: 35,
      maxHealth: 35,
      attack: 12,
      level: 1,
      experience: 0,
      evolutionLevel: 12,
      image: 'assets/player-pokemon/Pikachu.png',
      locked: true,
    },
    {
      id: 44,
      commonId: 4,
      name: 'Raichu',
      currentHealth: 90,
      maxHealth: 90,
      attack: 30,
      level: 12,
      experience: 0,
      image: 'assets/player-pokemon/Raichu.jpg',
      locked: true,
    },
    {
      id: 5,
      commonId: 5,
      name: 'Eevee',
      currentHealth: 30,
      maxHealth: 30,
      attack: 10,
      level: 1,
      experience: 0,
      image: 'assets/player-pokemon/Eevee.png',
      locked: true,
    },
    // {
    //   id: 6,
    //   commonId: 5,
    //   name: 'Mew',
    //   currentHealth: 30,
    //   maxHealth: 30,
    //   attack: 10,
    //   level: 1,
    //   experience: 0,
    //   image: 'assets/player-pokemon/Eevee.png',
    //   locked: true,
    // },
    {
      id: 7,
      commonId: 7,
      name: 'Articuno',
      currentHealth: 90,
      maxHealth: 90,
      attack: 30,
      level: 1,
      evolutionLevel: 18,
      experience: 0,
      image: 'assets/player-pokemon/Articuno.jpg',
      locked: true,
    },
    {
      id: 8,
      commonId: 8,
      name: 'Zapdos',
      currentHealth: 80,
      maxHealth: 80,
      attack: 35,
      level: 1,
      experience: 0,
      evolutionLevel: 18,
      image: 'assets/player-pokemon/Zapdos.jpg',
      locked: true,
    },
    {
      id: 9,
      commonId: 9,
      name: 'Moltres',
      currentHealth: 70,
      maxHealth: 70,
      attack: 40,
      level: 1,
      evolutionLevel: 18,
      experience: 0,
      image: 'assets/player-pokemon/Moltres.jpg',
      locked: true,
    },
  ]);
}
